# Generated by Django 5.0 on 2025-01-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='course',
            new_name='courses',
        ),
    ]
