# Generated by Django 5.0 on 2025-01-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_courses', to='app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_tags', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='courses',
            field=models.ManyToManyField(related_name='categories', to='app.course'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='courses',
            field=models.ManyToManyField(related_name='tags', to='app.course'),
        ),
    ]
