# Generated by Django 5.0 on 2025-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_category_course_tag_alter_category_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='about',
            new_name='paragraph1',
        ),
        migrations.AddField(
            model_name='course',
            name='paragraph2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='paragraph3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='paragraph4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
