# Generated by Django 5.0 on 2025-01-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='categories', to='app.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
