# Generated by Django 5.0 on 2025-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.ManyToManyField(to='app.lecture'),
        ),
    ]
